image: node:11-alpine

cache:
  paths:
    - node_modules/

before_script:
  - yarn

build:
  stage: build
  tags:
    - vgm
    - library
    - docker
  script:
    - npm run build

test:
  stage: test
  tags:
    - vgm
    - library
    - docker
  script:
    - npm run test

deploy:
  image: node:11
  stage: deploy
  tags:
    - vgm
    - library
  script:
    - yarn build
    - npm run test:prod && npm run build
    # - yarn report-coverage
    - yarn semantic-release
  only:
    - master
